[font]
size = 10
builtin_box_drawing = true

[font.normal]
family = "FiraCode Nerd Font Mono"

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"

[window]
opacity = 1
blur = true
startup_mode = "Windowed"
decorations = "Full"

[terminal.shell]
program = "zellij"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Underline"
blinking = "On"

[selection]
save_to_clipboard = true

[scrolling]
history = 10000

[keyboard]
bindings = [
  { key = "Return", mods = "Alt", action = "ToggleFullscreen" },
]
