# lazygit — https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

gui:
  nerdFontsVersion: "3" # FiraCode Nerd Font est installée -> icônes.
  showFileTree: true # arbre de fichiers plutôt que liste à plat.
  showRandomTip: false
  showCommandLog: false # masque le panneau de log en bas.
  border: rounded
  skipRewordInEditorWarning: true
  mouseEvents: false
  theme: # Catppuccin Mocha
    activeBorderColor:
      - "#cba6f7"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#cba6f7"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"
    searchingActiveBorderColor:
      - "#f9e2af"
os:
  editPreset: "helix" # ouvre les fichiers (touche `e`) dans Helix.
git:
  pagers:
    - colorArg: always
  parseEmoji: true
customCommands:
  - key: "C"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
