# Example

# ==========================================================
# Example
# ==========================================================

# Tags: banana
# Host my-server
#     HostName 10.0.0.12
#     User deploy
#     ProxyJump my-bastion
#     LocalForward 8080 localhost:8080
#     IdentityFile ~/.ssh/id_ed25519
